### ISSUE TITLE
EPIC: HSM v2.0

### ISSUE THREAD

**Issue by amoose** [18F/10x-MLaaS#52]
## 10x Qualitative Data User story 
As a **USAgov analytics team member**
I want to ** **
So that I 
  
## Acceptance criteria
- [ ] HSM service running in the cloud that accepts unclassified survey data and returns classified survey data via simple user interface. **(Issue #58 )**
- [ ] Replace HSMs data persistence with a relational database. **(Issue #57  )**
- [ ] Service can run in cloud.gov and use SecureAuth for authentication **(Issue #59 )**
- [ ] The HSM service has a simple web interface for uploading, retrieving, classifying and training events **(Issue #60 )**

**Comment by TiffanyAndrews** [comment]
ARCHIVE
