### ISSUE TITLE
Allow HSM model to be trained each time it runs

### ISSUE THREAD

**Issue by TiffanyAndrews** [18F/10x-MLaaS#80]
## 10x Qualitative Data User story 
As a business user, I want the HSM to become "smarter"after each run so that the spam algorithm precision to predict accurately improves and I spend less time correct results. 
  
## Acceptance criteria
- [ ] Validated data is imported back into the model 
- [ ] The validated data is saved in the central db
- [ ] The user is notified via messaging that 
   1) MeL is waiting for validated data 
   2) validated data has been received and saved. 

## Todos
- Identify essential data that is needed to retrain, not redownload.
- Update the database to only save these essential data, along with any data from the spreadsheet (create a new simple schema to save the data)
- Abandon the original database schema and make sure I am not neglecting any important features that are needed
- Update code to reflect the use of new database tables
- Recreate the new database with all the data
