### ISSUE TITLE
Store essential data to save in datastore

### ISSUE THREAD

**Issue by amymok** [18F/10x-MLaaS#91]
## 10x Qualitative Data User story 
As a data scientist, I want to make sure essential data are being saved in a datastore so that I can use the data to retrain the model and also will not include any duplicate data which can skew the model. 
  
## Acceptance criteria
- [x] Database schema for essential data is defined
- [x] Ability to load data into this new schema that had already been processed before

## Todos
- [x] Identify essential data that is needed to retrain, not redownload.
- [x] Update the database to only save these essential data, along with any data from the spreadsheet (create a new simple schema to save the data)

## Risks
- Not easy to identify essential data
- the original database schema is really necessary for the success of the tool (then it means I need to revisit to remove the performance issues)

**Comment by amymok** [comment]
This is a subtask for #80
