### ISSUE TITLE
Update the codebase to use the new datastore schema

### ISSUE THREAD

**Issue by amymok** [18F/10x-MLaaS#92]
## 10x Qualitative Data User story 
As a developer, I want to update the codebase so it is using this new datastore schema so that we can make use of the data to retrain and predict. 
  
## Acceptance criteria
- [x] Data saved can be used to retrain model

## Todos:
- [x] Abandon the original database schema and make sure I am not neglecting any important features that are needed
- [x] Update code to reflect the use of new database tables

## Risks:
- There are a lot of code changes needed to be done

**Comment by amymok** [comment]
This is a subtask for #80
